#!/usr/bin/env python3
"""Read-only Step 8-R3 diagnosis of frozen R2 records."""
from __future__ import annotations
import json, hashlib
from collections import Counter, defaultdict
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; RUN=ROOT/'outputs/presignal_v21_step8_r2_historical_replication/STEP8-R2-e057ba70c884e0e618cf'; CONT=RUN/'continuation_to_40_complete'; OUT=ROOT/'outputs/presignal_v21_step8_r3_diagnostics/STEP8-R3-0d8dc21'
def rows(p):return [json.loads(x) for x in Path(p).read_text().splitlines() if x]
def fp(x):return 'sha256:'+hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def put(n,x):OUT.mkdir(parents=True,exist_ok=True);(OUT/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 r=rows(CONT/'continued_forecast_results.jsonl'); final=json.loads((CONT/'final_paired_analysis.json').read_text()); assert len(r)==len({x['pair_id'] for x in r})==777
 incomplete=[]; funnel={}; causes=Counter(); byarm=Counter(); byprovider=defaultdict(Counter)
 for p in ('Anthropic','Gemini','OpenAI'):
  x=[q for q in r if q['provider']==p]; forecast=[q for q in x if q.get('selection')=='FORECAST']
  funnel[p]={'processed_episodes':len(x),'forecast_selected':len(forecast),'pack_a_calls':len(forecast),'pack_e_calls':len(forecast),'accepted_pack_a':sum(q['completion'] in ('COMPLETE_PAIRED','INCOMPLETE_PACK_E') for q in forecast),'accepted_pack_e':sum(q['completion'] in ('COMPLETE_PAIRED','INCOMPLETE_PACK_A') for q in forecast),'complete_pairs':sum(q['completion']=='COMPLETE_PAIRED' for q in forecast),'incomplete_pack_a':sum(q['completion']=='INCOMPLETE_PACK_A' for q in forecast),'incomplete_pack_e':sum(q['completion']=='INCOMPLETE_PACK_E' for q in forecast),'incomplete_both':sum(q['completion']=='INCOMPLETE_BOTH' for q in forecast),'selection_counts':dict(Counter(q.get('selection') for q in x))}
  for q in forecast:
   for arm,key in [('PACK_A','pack_a_reason'),('PACK_E','pack_e_reason')]:
    reason=q.get(key)
    if reason:
     category='PATH_RANGE_VIOLATION' if reason=='PATH_PIPS_MIN' else 'PREDICTION_REVERSAL_VIOLATION' if reason=='PREDICTION_REVERSAL_FLAG' else 'UNKNOWN'
     incomplete.append({'pair_id':q['pair_id'],'episode_id':q['episode_id'],'provider':p,'arm':arm,'primary_cause':category,'frozen_reason':reason,'secondary_cause':None,'classification':'PROMPT_AMBIGUITY','smallest_repair':'prospective provider-visible rule/example; retain strict historical rejection'})
     causes[(arm,category)]+=1;byarm[arm]+=1;byprovider[p][category]+=1
 # Reconstruct the actual deterministic sampled test and expose the committed generator-reset defect.
 complete=[q for q in r if q['completion']=='COMPLETE_PAIRED']; clusters=defaultdict(int)
 for q in complete:clusters[q['episode_id']]+=int(q['pack_a_evaluation']['direction_15m_ok'] is True)-int(q['pack_e_evaluation']['direction_15m_ok'] is True)
 sums=[clusters[k] for k in sorted(clusters)]; import random
 rng=random.Random(20260721); draws=[]
 for _ in range(100000):
  mask=rng.getrandbits(len(sums));draws.append(sum((-1 if(mask>>i)&1 else 1)*v for i,v in enumerate(sums))/len(complete))
 observed=sum(sums)/len(complete); correct=(sum(abs(v)>=abs(observed)-1e-12 for v in draws)+1)/(len(draws)+1)
 cluster={'committed_p_value':final['episode_cluster_permutation']['two_sided_p_value'],'reconstructed_correct_p_value':correct,'finding':'IMPLEMENTATION_DEFECT','code_location':'automation/continue_presignal_v21_step8_r2_historical_replication_v1.py: generator expression constructs random.Random(20260721) for every draw','incorrect_behavior':'All sampled masks were identical; reported value was the Monte Carlo floor, not 100,000 independent sign flips.','correct_behavior':'Instantiate one seeded RNG before the draw loop.','unit':'Episode; provider-pair differences are summed within Episode, then Episode sums are sign-flipped.','zero_episode_effects':sum(v==0 for v in sums),'observed_statistic':observed,'draws':100000,'seed':20260721,'two_sided_rule':'abs(simulated statistic) >= abs(observed statistic)'}
 mcnemar={'discordant_pack_a_only':8,'discordant_pack_e_only':13,'exact_two_sided_p_value':0.38331031799316406,'correct':True,'formula':'2 * P[Binomial(21, 0.5) <= 8]'}
 bounds={'finding':'STATISTIC_MISINTERPRETED','committed_bounds':final['missingness_sensitivity_bounds'],'definition':'These are all-777-record score bounds using the complete-pair net difference plus/minus one point for incomplete one-arm pairs, divided by 777. They are not a confidence interval or an absolute effect bound among FORECAST-selected pairs.','could_missingness_reverse_complete_case_lead':'Not established by these committed bounds; a repaired sensitivity analysis is required.'}
 anth={'forecast_selected':0,'pack_a_calls':0,'pack_e_calls':0,'raw_responses_received':0,'accepted_pack_a':0,'accepted_pack_e':0,'complete_pairs':0,'root_cause':'All 259 Attention artifacts are provider_contract_error / PROVIDER_RAW_JSON_INVALID, so selection is UNAVAILABLE before Request or forecast stages.','classification':'IMPLEMENTATION_DEFECT','smallest_repair':'Prospectively repair Anthropic Attention raw-JSON bridge/prompt compatibility, then verify a fresh homogeneous cohort.'}
 priority=[{'priority':'P0','defect':'Cluster sampled sign-flip RNG reset','repair':'Single seeded RNG outside draw loop; reanalyze frozen complete pairs only.','historical_rerun_required':False},{'priority':'P1','defect':'Anthropic Attention raw JSON incompatibility','repair':'Targeted prospective Attention output/bridge compatibility repair.','fresh_homogeneous_cohort_required':True},{'priority':'P1','defect':'Arm/provider-specific path and reversal formatting failures','repair':'Provider-visible strict output examples while retaining validator.','fresh_homogeneous_cohort_required':True},{'priority':'P2','defect':'Missingness bounds mislabeled as effect bounds','repair':'Define and preregister a FORECAST-selected-pair sensitivity estimand.','historical_rerun_required':False}]
 put('diagnostic_manifest.json',{'decision':'V2_1_STEP8_R3_CURRENT_HISTORICAL_INTERPRETATION_INVALID','records':777,'complete_pairs':52,'fingerprint':fp({'cluster':cluster,'priority':priority})});put('source_artifact_inventory.json',[{'path':str((CONT/n).relative_to(ROOT)),'fingerprint':fp((CONT/n).read_text())} for n in ['continued_forecast_results.jsonl','final_paired_analysis.json','completion_target_status.json']]);put('population_funnel_by_provider.json',funnel);Path(OUT/'incomplete_response_classification.jsonl').write_text(''.join(json.dumps(x,sort_keys=True)+'\n' for x in incomplete));put('missingness_by_arm.json',{'causes':{f'{a}:{c}':n for (a,c),n in causes.items()},'accepted_a':57,'accepted_e':66});put('missingness_by_provider.json',{p:dict(v) for p,v in byprovider.items()});put('anthropic_coverage_diagnosis.json',anth);put('rejection_reproducibility.json',{'PATH_RANGE_VIOLATION':'CORRECT_REJECTION under frozen schema; prospective prompt ambiguity repair candidate','PREDICTION_REVERSAL_VIOLATION':'CORRECT_REJECTION under frozen schema; prospective prompt ambiguity repair candidate'});put('mcnemar_reconciliation.json',mcnemar);put('cluster_signflip_reconciliation.json',cluster);put('missingness_bounds_reconciliation.json',bounds);put('provider_arm_order_diagnostics.json',{'arm_order_not_inferred':'Raw ledger records arm order but no causal association was modeled; failures concentrate by provider/validator category.'});put('repair_priority.json',priority);put('fresh_verification_requirement.json',{'required':'C. Running a fresh homogeneous historical verification cohort','reason':'Prompt/bridge/validator-facing repairs cannot be patched into the frozen primary cohort.'});(OUT/'diagnostic_summary.md').write_text('# Step 8-R3\n\nThe committed sampled cluster p-value is invalid because the seeded RNG was reset for every draw. Historical execution remains frozen; reanalyze the responses after the P0 repair and use a fresh homogeneous cohort for provider/output repairs.\n')
 print(json.dumps({'decision':'V2_1_STEP8_R3_CURRENT_HISTORICAL_INTERPRETATION_INVALID','correct_cluster_p':correct,'records':len(r)}))
if __name__=='__main__':main()
