"""Call-free R3 fresh homogeneous cohort preparation."""
from __future__ import annotations
import json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from automation import run_presignal_v21_step8_r2_historical_replication_v1 as r2
from automation import presignal_v21_historical_verification_r3_contract_v1 as r3
R2=ROOT/'outputs/presignal_v21_step8_r2_historical_replication/STEP8-R2-e057ba70c884e0e618cf'; OUT=ROOT/'outputs/presignal_v21_step8_r3_repair/STEP8-R3-REPAIR-df9c25e'
def write(n,x):OUT.mkdir(parents=True,exist_ok=True);(OUT/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 _,eligible,_,source=r2.recover_population(); original={x['episode_id'] for x in json.loads((R2/'frozen_execution_population.json').read_text())['episodes']}; continued={json.loads(x)['episode_id'] for x in (R2/'continuation_to_40_complete/continued_population.jsonl').read_text().splitlines() if x}; selected=[x for x in eligible if x['episode_id'] not in original|continued][:400]
 contract=r3.spec(); missing={'estimand':'absolute Pack A-minus-Pack E 15-minute correctness among FORECAST-selected provider/Episode pairs','complete_case':'mean paired difference among complete pairs','worst_pack_a':'all Pack-A-missing arms incorrect and Pack-E-missing arms correct; incomplete-both excluded symmetrically','worst_pack_e':'reverse assumptions; incomplete-both excluded symmetrically','not_a_confidence_interval':True}
 manifest={'contract':contract,'selection_order':['scheduled_release_ts','session_id','episode_id'],'excluded_prior_r2_episodes':len(original|continued),'fresh_execution_episodes':len(selected),'minimum_complete_episodes':40,'target_complete_episodes':60,'maximum_processed_episodes':400,'providers':{'Anthropic':'claude-haiku-4-5','Gemini':'gemini-2.5-flash-lite','OpenAI':'gpt-4o-mini-2024-07-18'},'provider_calls':0,'acquisition_calls':0,'apps_script_calls':0}
 write('repair_manifest.json',{'decision':'V2_1_STEP8_R3_TARGETED_REPAIRS_VALIDATED','fresh_status':'V2_1_STEP8_R3_FRESH_HISTORICAL_VERIFICATION_READY'});write('r3_contract_manifest.json',contract);write('contract_diff.json',{'parent':r3.PARENT_CONTRACT_VERSION,'deltas':r3.PROMPT_RULES,'scientific_semantics_changed':False});write('missingness_estimand.json',missing);write('missingness_sensitivity_preregistration.json',missing);write('fresh_verification_population_plan.json',{'safe_eligible_episodes':len(eligible),'selected':len(selected),'episodes':selected});write('fresh_verification_quality_gates.json',{'anthropic_fixture_complete_pair_required':True,'all_routes_dry_run':True,'paired_completion_target':0.85,'max_arm_completion_imbalance':0.05,'unexplained_contract_failures':0,'model_substitutions':0,'leakage':0,'cutoff_violations':0});write('fresh_verification_call_budget.json',{'maximum_forecast_arms':2400,'execution_not_authorized':True});write('fresh_verification_manifest.json',manifest);write('prospective_pause_validation.json',{'p12_status':'PAUSED_PENDING_HISTORICAL_VALIDATION','prospective_calls':0});write('historical_immutability_validation.json',{'r2_execution_unchanged':True});write('repair_summary.md','# Step 8-R3 Repair\n\nCall-free compatibility fixtures and a fresh homogeneous cohort plan are frozen.\n');print(json.dumps(manifest))
if __name__=='__main__':main()
