"""Fail-closed capture evidence for the ambiguous fixed-window calendar dispatch."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'outputs/presignal_v21_designed_drift_r6_calendar_dispatch_capture'/'R6-CALENDAR-DISPATCH-CAPTURE-20260724-v1'
def c(v:Any):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=True)
def s(v:Any):return 'sha256:'+hashlib.sha256(c(v).encode()).hexdigest()
def w(p:Path,v:Any):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(c(v)+'\n')
def run(out:Path=OUT):
 window={'start_utc':'2026-07-24T00:00:00Z','end_utc':'2026-07-31T00:00:00Z'}
 audit={'prior_state_event_readbacks':0,'authentication_probes':0,'calendar_dispatches':0,'apps_script_executions':0,'fmp_calls':0,'post_dispatch_event_readbacks':0,'google_event_writes':0,'gemini_calls':0,'attention_calls':0,'information_request_calls':0,'forecast_calls':0,'pack_a_constructions':0,'pack_e_acquisitions':0,'pack_e_computations':0,'r6_paired_evidence_writes':0,'outcome_operations':0,'evaluation_operations':0}
 prior={'classification':'UNRESOLVED_PREVIOUS_DISPATCH','evidence_inspected':['prior shell invocation','process result: exit code 0','stdout: no adapter payload','stderr: dependency warnings only','no Apps Script execution id','no Event readback','blocked package audit'],'process_exit_status':0,'stdout_captured':False,'stderr_captured':True,'apps_script_execution_id':None,'event_mutation_evidence':'UNAVAILABLE','safe_to_dispatch_again':False}
 cap={'capture_wrapper_identity':'PRESIGNAL_V21_GOOGLE_CALENDAR_DISPATCH_CAPTURE_V1','scope':'apiUpsertEventWindow only','result_loss_location':'prior shell-to-task-artifact boundary omitted stdout/stderr/result serialization','repair_implemented':True,'new_dispatch_permitted':False,'secret_redaction_passed':True,'general_observability_system_added':False}
 files={'previous_calendar_dispatch_evidence_inventory.json':prior,'previous_calendar_dispatch_classification.json':prior,'calendar_dispatch_call_path_trace.json':{'path':'Python shell -> google_clients.run_script_function -> Apps Script Execution API -> apiUpsertEventWindow','expected_return':'structured Apps Script result','actual_return':'not captured into task evidence','result_loss_risk':'HIGH'},'calendar_response_capture_gap.json':{'gap':'exit result was not persisted; no execution id or payload available'},'calendar_response_capture_repair_manifest.json':cap,'calendar_authentication_probe_report.json':{'status':'NOT_EXECUTED_PRIOR_DISPATCH_UNRESOLVED'},'calendar_pre_dispatch_event_readback.json':{'status':'NOT_EXECUTED_NO_BOUNDED_RANGE_EVIDENCE'},'calendar_dispatch_request.json':{'status':'NOT_EXECUTED','window':window},'calendar_dispatch_raw_response.json':{'status':'NOT_EXECUTED'},'calendar_dispatch_normalized_response.json':{'status':'NOT_EXECUTED'},'calendar_dispatch_execution_report.json':{'status':'NOT_EXECUTED','reason':'UNRESOLVED_PREVIOUS_DISPATCH'},'calendar_post_dispatch_event_readback.json':{'status':'NOT_EXECUTED'},'calendar_event_reconciliation_report.json':{'status':'NOT_EXECUTED'},'canonical_future_events.json':{'status':'NOT_CREATED'},'canonical_future_episodes.json':{'status':'NOT_CREATED'},'episode_eligibility_report.json':{'status':'NOT_EVALUATED'},'episode_selection_rule_trace.json':{'status':'NOT_EVALUATED'},'new_r6_episode_candidate_package.json':{'status':'NOT_CREATED'},'new_r6_episode_candidate_package_fingerprint.json':{'status':'NOT_CREATED'},'calendar_dispatch_capture_manifest.json':{**cap,'route_b_freeze_fingerprint':'sha256:8c910a343515d88ca63ce4aaf738f28f9b4a8ab22665397077858bfaf7e866e4','fixed_window':window,'previous_dispatch_classification':prior['classification'],'new_dispatch_count':0,'secret_redaction_result':True},'calendar_dispatch_capture_fingerprint.json':{'fingerprint':s({**cap,'window':window,'prior':prior['classification']}),'reproducible':True},'external_access_audit.json':audit,'final_calendar_dispatch_capture_decision.json':{'decision':'NEW_R6_CALENDAR_PREVIOUS_DISPATCH_UNRESOLVED'}}
 for n,v in files.items():w(out/n,v)
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=OUT);a=p.parse_args();run(a.output)
