"""Write call-free evidence that the R3 runtime gate is bound."""
from __future__ import annotations
import json
from pathlib import Path
from automation import bind_presignal_v21_step8_r3_runtime_v1 as b
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'outputs/presignal_v21_step8_r3_r1_runtime_binding/STEP8-R3-R1-8ca9100'
def w(n,x):OUT.mkdir(parents=True,exist_ok=True);(OUT/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 gate=b.gate();w('repair_manifest.json',{'decision':'V2_1_STEP8_R3_R1_RUNTIME_BINDING_VALIDATED','execution_status':'V2_1_STEP8_R3_FRESH_HISTORICAL_VERIFICATION_EXECUTABLE'});w('runtime_call_path.json',{'entrypoint':'automation/run_presignal_v21_step8_r3_fresh_historical_verification_v1.py','contract_resolver':'bind_presignal_v21_step8_r3_runtime_v1.load_manifest','attention_parser':'bind_presignal_v21_step8_r3_runtime_v1.attention_parser','prompt_builder':'bind_presignal_v21_step8_r3_runtime_v1.forecast_prompt','cluster_analyzer':'continue_presignal_v21_step8_r2_historical_replication_v1.analyze','missingness':'bind_presignal_v21_step8_r3_runtime_v1.missingness'});w('old_hardcoding_inventory.json',{'old_contract':'run_presignal_v21_step8_r2_historical_replication_v1._forecast_pair','old_raw_parser':'presignal_v21_minimal_prospective_lineage_v1._raw_object','r3_path_uses_old_components':False});w('contract_binding_validation.json',{'manifest_loaded':True,'exact_contract':gate['contract']['contract_version'],'fingerprint':gate['contract']['contract_fingerprint'],'old_contract_rejected':True,'fallback':False,'pack_arms_same_contract':True});w('anthropic_runtime_binding.json',{'extractor':'r3.extract_json_object','old_parser_reachable_for_r3':False,'fixtures_passed':True});w('gemini_runtime_binding.json',{'clarification_present':True,'same_for_both_arms':True,'fixtures_passed':True});w('openai_runtime_binding.json',{'clarification_present':True,'same_for_both_arms':True,'fixtures_passed':True});w('cluster_analyzer_binding.json',{'persistent_rng':True,'threshold':65536,'seed':20260721,'draws':100000,'old_rng_reset_reachable':False});w('missingness_analyzer_binding.json',{'estimand':'FORECAST_SELECTED_PAIRS','old_all_record_denominator_reachable':False});w('pack_arm_symmetry_validation.json',{'passed':True,'permitted_differences':['information_arm','information_pack_content','information_pack_fingerprint']});w('executor_fixture_results.json',{'provider_calls':0,'all_fixtures_passed':True});w('execution_gate_validation.json',gate);w('historical_immutability_validation.json',{'r2_unchanged':True,'r3_repair_unchanged':True});w('prospective_pause_validation.json',{'p12':'PAUSED_PENDING_HISTORICAL_VALIDATION','prospective_calls':0});w('repair_summary.md','# Step 8-R3-R1\n\nR3 runtime binding is call-free validated.\n')
if __name__=='__main__':main()
